// Placeholder products for showcasing animations
export const placeholderProducts = [
  {
    productId: 'placeholder-1',
    name: 'Grace Elegance Set',
    price: 129.99,
    description: 'A timeless two-piece ensemble featuring a flowing midi skirt and coordinating blouse, perfect for Sunday service or special occasions.',
    imageUrls: ['https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&h=1000&fit=crop'],
    visible: true,
  },
  {
    productId: 'placeholder-2',
    name: 'Faith & Fashion Dress',
    price: 98.50,
    description: 'Sophisticated A-line dress with elegant detailing, designed to make you feel confident and beautiful in worship.',
    imageUrls: ['https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=800&h=1000&fit=crop'],
    visible: true,
  },
  {
    productId: 'placeholder-3',
    name: 'Modesty Chic Ensemble',
    price: 145.00,
    description: 'Luxurious three-piece set combining modesty with contemporary style, featuring premium fabrics and impeccable tailoring.',
    imageUrls: ['https://images.unsplash.com/photo-1617019114583-affb34d1b3cd?w=800&h=1000&fit=crop'],
    visible: true,
  },
  {
    productId: 'placeholder-4',
    name: 'Divine Worship Attire',
    price: 112.75,
    description: 'Elegant coordinated outfit that transitions seamlessly from worship to brunch, embodying grace and sophistication.',
    imageUrls: ['https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800&h=1000&fit=crop'],
    visible: true,
  },
  {
    productId: 'placeholder-5',
    name: 'Sunday Best Collection',
    price: 165.00,
    description: 'Premium Sunday wear set that combines tradition with modern elegance, crafted from the finest materials.',
    imageUrls: ['https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&h=1000&fit=crop'],
    visible: true,
  },
  {
    productId: 'placeholder-6',
    name: 'Praise & Style Outfit',
    price: 89.99,
    description: 'Comfortable yet sophisticated ensemble perfect for choir practice or casual worship gatherings.',
    imageUrls: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800&h=1000&fit=crop'],
    visible: true,
  },
  {
    productId: 'placeholder-7',
    name: 'Reverence Ensemble',
    price: 178.50,
    description: 'Luxurious formal wear that honors both your faith and personal style, ideal for special church events.',
    imageUrls: ['https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=800&h=1000&fit=crop'],
    visible: true,
  },
  {
    productId: 'placeholder-8',
    name: 'Blessed Beauty Set',
    price: 124.25,
    description: 'Versatile coordinated pieces that work together or separately, bringing elegance to every occasion.',
    imageUrls: ['https://images.unsplash.com/photo-1618932260643-eee4a2f652a6?w=800&h=1000&fit=crop'],
    visible: true,
  },
];
